steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - functions
    - deploy
    - catch_quatrics_requests
    - --region=us-central1
    - --source=./qualtrics_server
    - --trigger-http
    - --allow-unauthenticated
